#!/bin/sh

# NAME: copy-files
# PATH: Current directory where files downloaded from github
# DESC: Copy eyesome scripts / command files to target directories
# DATE: September ?? 2018.

if [ $(id -u) != 0 ]; then # root powers needed to call this script
    echo >&2 $0 must be called with sudo powers
    exit 1
fi

# Reminder to install yad for eyesome-cfg.sh program
command -v yaasdfd >/dev/null 2>&1 || echo  \
        "\nyad package is required for eyesome-cfg.sh but it is not installed.
Remember to install it later using 'sudo apt install yad'.\n"

# TODO: Put in check for inotify-tools after monitor-eyesome.sh created.

install -v ./eyesome.sh             /usr/local/bin/
install -v ./eyesome-cfg.sh         /usr/local/bin/
install -v ./eyesome-src.sh         /usr/local/bin/
install -v ./eyesome-sun.sh         /usr/local/bin/
install -v ./wake-eyesome.sh        /usr/local/bin/
install -v ./start-eyesome          /etc/cron.d/
install -v ./daily-eyesome-sun      /etc/cron.daily/
install -v ./systemd-wake-eyesome   /lib/systemd/system-sleep/

exit 0

# Future uninstall section
rm -v -f /usr/local/bin/eyesome.sh
rm -v -f /usr/local/bin/eyesome-cfg.sh
rm -v -f /usr/local/bin/eyesome-src.sh
rm -v -f /usr/local/bin/eyesome-sun.sh
rm -v -f /usr/local/bin/wake-eyesome.sh
rm -v -f /etc/cron.d/start-eyesome
rm -v -f /etc/cron.daily/daily-eyesome-sun
rm -v -f /lib/systemd/system-sleep/systemd-wake-eyesome

