#!/bin/sh

# NAME: systemd-wake-eyesome
# PATH: /lib/systemd/system-sleep/
# DESC: Restart eyesome.sh when resuming from suspend
# CALL: Automatically called by systemd during suspends and resumes
# DATE: August 2017. Modified: September 21, 2018.

# NOTE: Wrapper script

/usr/local/bin/wake-eyesome.sh "$@"

exit 0
